# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ebZTAdK8b_X_3R6hM7Z9Z3Lgi0wORyR-
"""

import streamlit as st
import pandas as pd
import joblib

# Cargar modelo
modelo = joblib.load("random_forest.pkl")
scaler = joblib.load("scaler.pkl")

st.title("Monitoreo de Sistema Hidráulico")

st.write(
    "Predicción de estabilidad del sistema hidráulico mediante Random Forest"
)

uploaded_file = st.file_uploader(
    "Cargar archivo CSV",
    type=["csv"]
)

if uploaded_file is not None:

    datos = pd.read_csv(uploaded_file)

    datos_scaled = scaler.transform(datos)

    predicciones = modelo.predict(datos_scaled)

    resultado = datos.copy()
    resultado["Prediccion"] = predicciones

    st.subheader("Resultados")

    st.dataframe(resultado)

    csv = resultado.to_csv(index=False)

    st.download_button(
        "Descargar resultados",
        csv,
        "predicciones.csv",
        "text/csv"
    )